<?php
// certificate.php — Certificado imprimible de sorteo

require_once __DIR__ . '/db.php';
require_once __DIR__ . '/config.php';

$id = trim($_GET['v'] ?? '');
if (!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $id)) {
    http_response_code(400); die('ID inválido');
}
$sorteo = get_sorteo($id);
if (!$sorteo || $sorteo['status'] !== 'done') {
    http_response_code(404); die('Sorteo no encontrado o aún no finalizado');
}
$all_winners = get_winners($id);
$winners = array_values(array_filter($all_winners, fn($w) => !$w['is_backup']));
$backups  = array_values(array_filter($all_winners, fn($w) =>  $w['is_backup']));
$opts = $sorteo['options'] ?? [];

// Fecha raw de la BD (UTC, tal como la guarda SQLite)
$drawn_at_raw = !empty($all_winners) ? ($all_winners[0]['drawn_at'] ?? '') : '';

// HMAC-SHA256: cubre id, video, fecha, comment_ids y autores — no falsificable sin la clave del servidor
$hmac_data   = implode('|', [
    $id,
    $sorteo['video_id'] ?? '',
    $drawn_at_raw,
    implode(',', array_column($winners, 'comment_id')),
    implode(',', array_column($winners, 'author')),
]);
$verify_hash = strtoupper(substr(hash_hmac('sha256', $hmac_data, SORTEO_HMAC_SECRET), 0, 32));

// Estado de bloqueo
$cert_video_set = video_set_from_sorteo($sorteo);
$cert_lock      = get_active_lock($cert_video_set);
$is_official    = $cert_lock && ($cert_lock['sorteo_id'] === $id);
$is_unofficial  = $cert_lock && ($cert_lock['sorteo_id'] !== $id);

// Número de orden entre sorteos del mismo conjunto de videos
$mismo_conjunto  = get_sorteos_mismo_conjunto($id);
$draw_number     = 1;
foreach ($mismo_conjunto as $i => $s) {
    if ($s['id'] === $id) { $draw_number = $i + 1; break; }
}
$draw_total = count($mismo_conjunto);

$lang = (trim($_GET['lang'] ?? 'es') === 'en') ? 'en' : 'es';
$cert_strings = [
    'es' => [
        'title'        => 'Certificado de Sorteo',
        'subtitle'     => 'Generado por mammoli.ar/sorteo',
        'video'        => 'Video',
        'drawn_at'     => 'Fecha del sorteo',
        'options'      => 'Opciones',
        'winners'      => 'Ganadores',
        'backups'      => 'Suplentes',
        'keyword'      => 'Filtro',
        'max_per_user' => 'Máx. por usuario',
        'min_likes'    => 'Mín. likes',
        'dates'        => 'Período',
        'from'         => 'desde',
        'to'           => 'hasta',
        'view_comment' => 'Ver comentario en YouTube ↗',
        'verification' => 'Verificación',
        'print_btn'    => '🖨️ Imprimir / Guardar PDF',
        'backup_badge' => 'Suplente',
        'winner_label' => 'Ganador',
        'winners_label'=> 'Ganadores',
        'no_filter'    => 'Sin filtro',
        'unlimited'    => 'Sin límite',
        'n_per_user'   => '{0} por usuario',
        'unique_user_yes' => 'Sí',
        'unique_user_no'  => 'No',
        'unique_user_label' => 'Usuario único',
        'draw_details' => 'Detalles del sorteo',
        'draw_number'         => 'N.º de sorteo para este conjunto',
        'draw_number_warning' => 'Este es el sorteo #{0} realizado para este conjunto de videos. Verificá la fecha y comparalo con el certificado original.',
        'official_badge'      => '✓ Sorteo oficial',
        'official_until'      => 'Marcado como oficial hasta {0}',
        'unofficial_warn'     => 'Este sorteo no está marcado como el oficial para este conjunto de videos.',
        'lock_panel_title'    => '🔒 Marcar como sorteo oficial',
        'lock_panel_desc'     => 'Bloqueá este conjunto de videos para que no se puedan realizar nuevos sorteos durante el período elegido. Este certificado aparecerá como el oficial en la verificación.',
        'lock_1d'             => '1 día',
        'lock_3d'             => '3 días',
        'lock_7d'             => '7 días',
        'lock_30d'            => '30 días',
        'lock_active_title'   => '🔐 Sorteo oficial activo',
        'lock_active_desc'    => 'Marcado como oficial hasta {0}. No se pueden realizar nuevos sorteos del mismo conjunto de videos.',
        'lock_btn_unlock'     => 'Desbloquear',
        'date_from_label' => 'Comentarios desde',
        'date_to_label'   => 'Comentarios hasta',
        'keyword_label'   => 'Filtro palabra clave',
        'generated_by'    => 'Generado por',
        'cert_subtitle_full' => 'Sorteo de comentarios de YouTube — resultado oficial',
        'scan_to_verify'  => 'Escanear para verificar',
        'method_title'    => 'Método de sorteo',
        'method_body'     => 'Los comentarios elegibles fueron mezclados en orden completamente aleatorio. Los primeros {0} de la lista resultante fueron declarados ganadores. El proceso es automático y no admite intervención manual — cada participante tuvo exactamente las mismas probabilidades de ser seleccionado.',
        'valid_until'     => 'Verificación disponible hasta',
    ],
    'en' => [
        'title'        => 'Giveaway Certificate',
        'subtitle'     => 'Generated by mammoli.ar/sorteo',
        'video'        => 'Video',
        'drawn_at'     => 'Draw date',
        'options'      => 'Options',
        'winners'      => 'Winners',
        'backups'      => 'Backup Winners',
        'keyword'      => 'Filter',
        'max_per_user' => 'Max per user',
        'min_likes'    => 'Min likes',
        'dates'        => 'Period',
        'from'         => 'from',
        'to'           => 'to',
        'view_comment' => 'View comment on YouTube ↗',
        'verification' => 'Verification',
        'print_btn'    => '🖨️ Print / Save PDF',
        'backup_badge' => 'Backup',
        'winner_label' => 'Winner',
        'winners_label'=> 'Winners',
        'no_filter'    => 'No filter',
        'unlimited'    => 'No limit',
        'n_per_user'   => '{0} per user',
        'unique_user_yes' => 'Yes',
        'unique_user_no'  => 'No',
        'unique_user_label' => 'Unique user',
        'draw_details' => 'Draw Details',
        'draw_number'         => 'Draw # for this set',
        'draw_number_warning' => 'This is draw #{0} for this set of videos. Verify the date and compare it against the original certificate.',
        'official_badge'      => '✓ Official Draw',
        'official_until'      => 'Marked as official until {0}',
        'unofficial_warn'     => 'This draw is not marked as the official one for this set of videos.',
        'lock_panel_title'    => '🔒 Mark as official draw',
        'lock_panel_desc'     => 'Lock this set of videos so no new draws can be created during the chosen period. This certificate will appear as the official one in verification.',
        'lock_1d'             => '1 day',
        'lock_3d'             => '3 days',
        'lock_7d'             => '7 days',
        'lock_30d'            => '30 days',
        'lock_active_title'   => '🔐 Official draw active',
        'lock_active_desc'    => 'Marked as official until {0}. No new draws can be created for the same set of videos.',
        'lock_btn_unlock'     => 'Unlock',
        'date_from_label' => 'Comments from',
        'date_to_label'   => 'Comments until',
        'keyword_label'   => 'Keyword filter',
        'generated_by'    => 'Generated by',
        'cert_subtitle_full' => 'YouTube comment giveaway — official result',
        'scan_to_verify'  => 'Scan to verify',
        'method_title'    => 'Draw Method',
        'method_body'     => 'All eligible comments were shuffled into a completely random order. The first {0} in the resulting list were declared winners. The process is fully automatic and does not allow manual intervention — every participant had exactly equal odds of being selected.',
        'valid_until'     => 'Verification available until',
    ],
];
$GLOBALS['_cs'] = $cert_strings[$lang];
function cs(string $key, ...$args): string {
    $s = $GLOBALS['_cs'][$key] ?? $key;
    foreach ($args as $i => $v) { $s = str_replace('{' . $i . '}', (string)$v, $s); }
    return htmlspecialchars($s, ENT_QUOTES, 'UTF-8');
}

$video_id    = htmlspecialchars($sorteo['video_id'] ?? '', ENT_QUOTES);
$video_title = htmlspecialchars($sorteo['video_title'] ?? 'Sin título', ENT_QUOTES);
$drawn_at    = $drawn_at_raw ?: date('Y-m-d H:i:s');
$drawn_at_fmt = gmdate('d/m/Y H:i', strtotime($drawn_at)) . ' UTC';

$num_winners_opt  = (int)($opts['num_winners'] ?? count($winners));
$keyword          = $opts['keyword'] ?? '';
$date_from        = $opts['date_from'] ?? '';
$date_to          = $opts['date_to'] ?? '';
$unique_users     = !empty($opts['unique_users']);
$valid_until_fmt  = gmdate('d/m/Y', strtotime($drawn_at . ' +365 days'));

function esc(string $s): string {
    return htmlspecialchars($s, ENT_QUOTES, 'UTF-8');
}
?>
<!DOCTYPE html>
<html lang="<?= $lang ?>">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= cs('title') ?> — <?= $video_title ?></title>
<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: Georgia, 'Times New Roman', serif;
    background: #f5f5f0;
    color: #1a1a1a;
    font-size: 15px;
    line-height: 1.6;
    padding: 24px 16px 48px;
}

.cert-wrap {
    max-width: 800px;
    margin: 0 auto;
    background: #fff;
    border: 1px solid #d4b896;
    border-radius: 4px;
    box-shadow: 0 2px 12px rgba(0,0,0,.12);
    overflow: hidden;
}

/* Header */
.cert-header {
    background: #fff;
    border-bottom: 3px solid #b8860b;
    padding: 32px 40px 24px;
    text-align: center;
}
.cert-header .cert-icon {
    font-size: 48px;
    display: block;
    margin-bottom: 10px;
}
.cert-header h1 {
    font-size: 28px;
    font-weight: 700;
    color: #7a5c00;
    letter-spacing: .03em;
    margin-bottom: 4px;
}
.cert-header .cert-subtitle {
    font-size: 13px;
    color: #888;
    font-style: italic;
}

/* Body */
.cert-body {
    padding: 32px 40px;
}

/* Sections */
.cert-section {
    margin-bottom: 28px;
}
.cert-section-title {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .1em;
    color: #b8860b;
    border-bottom: 1px solid #e8d5a3;
    padding-bottom: 6px;
    margin-bottom: 14px;
}

/* Video info */
.cert-video-title {
    font-size: 16px;
    font-weight: 700;
    color: #1a1a1a;
    margin-bottom: 6px;
}
.cert-video-link {
    font-size: 13px;
    color: #1a6bb8;
    word-break: break-all;
    text-decoration: none;
}
.cert-video-link:hover { text-decoration: underline; }
.cert-video-id {
    font-size: 12px;
    color: #888;
    margin-top: 4px;
    font-family: 'Courier New', monospace;
}

/* Details table */
.cert-details {
    display: flex;
    flex-wrap: wrap;
    gap: 8px 32px;
}
.cert-detail-item {
    display: flex;
    flex-direction: column;
    gap: 2px;
}
.cert-detail-label {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: .05em;
    color: #999;
    font-family: Arial, sans-serif;
}
.cert-detail-value {
    font-size: 14px;
    font-weight: 600;
    color: #1a1a1a;
}

/* Winners list */
.cert-winner-list {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 14px;
}
.cert-winner-item {
    display: flex;
    gap: 14px;
    align-items: flex-start;
    padding: 14px 16px;
    background: #fdfaf4;
    border: 1px solid #e8d5a3;
    border-radius: 4px;
}
.cert-winner-pos {
    font-size: 20px;
    font-weight: 900;
    color: #b8860b;
    min-width: 28px;
    text-align: center;
    flex-shrink: 0;
    line-height: 1.3;
    font-family: Arial, sans-serif;
}
.cert-winner-pos.pos-1 { color: #c8940f; }
.cert-winner-pos.pos-2 { color: #6b7280; }
.cert-winner-pos.pos-3 { color: #92400e; }
.cert-winner-body { flex: 1; min-width: 0; }
.cert-winner-author {
    font-size: 15px;
    font-weight: 700;
    color: #1a1a1a;
    margin-bottom: 3px;
}
.cert-winner-comment {
    font-size: 13px;
    color: #555;
    font-style: italic;
    word-break: break-word;
    margin-bottom: 4px;
}
.cert-winner-link {
    font-size: 12px;
    color: #1a6bb8;
    text-decoration: none;
    font-family: Arial, sans-serif;
}
.cert-winner-link:hover { text-decoration: underline; }

/* Backups section */
.cert-backup-list {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 10px;
}
.cert-backup-item {
    display: flex;
    gap: 14px;
    align-items: flex-start;
    padding: 12px 16px;
    background: #f9f9f9;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
    opacity: .85;
}
.cert-backup-pos {
    font-size: 15px;
    font-weight: 700;
    color: #888;
    min-width: 28px;
    text-align: center;
    flex-shrink: 0;
    font-family: Arial, sans-serif;
}
.cert-backup-body { flex: 1; min-width: 0; }
.cert-backup-label {
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: .08em;
    color: #999;
    font-family: Arial, sans-serif;
    margin-bottom: 2px;
}
.cert-backup-author {
    font-size: 14px;
    font-weight: 600;
    color: #444;
}
.cert-backup-comment {
    font-size: 12px;
    color: #777;
    font-style: italic;
    word-break: break-word;
    margin-top: 2px;
}
.cert-backup-link {
    font-size: 12px;
    color: #1a6bb8;
    text-decoration: none;
    font-family: Arial, sans-serif;
}
.cert-backup-link:hover { text-decoration: underline; }

/* Footer */
.cert-footer {
    border-top: 2px solid #e8d5a3;
    padding: 18px 40px;
    background: #fdfaf4;
}
.cert-footer-inner {
    display: flex;
    align-items: center;
    gap: 20px;
}
.cert-footer-text { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 5px; }
.cert-footer-hash {
    font-size: 13px;
    font-family: 'Courier New', monospace;
    color: #444;
    word-break: break-all;
}
.cert-footer-hash strong { color: #7a5c00; }
.cert-footer-meta {
    font-size: 11px;
    color: #999;
    font-family: Arial, sans-serif;
}
.cert-footer-meta a { color: #888; text-decoration: none; }
.cert-footer-meta a:hover { text-decoration: underline; }
.cert-footer-qr { flex-shrink: 0; text-align: center; }
.cert-footer-qr a { display: block; }
.cert-footer-qr img { display: block; border-radius: 4px; border: 1px solid #e8d5a3; }
.cert-footer-qr-label {
    font-size: 9px;
    color: #b8860b;
    margin-top: 4px;
    font-family: Arial, sans-serif;
    text-transform: uppercase;
    letter-spacing: .05em;
}
@media print {
    .cert-footer-qr a { pointer-events: none; }
}

/* Print button */
.no-print {
    text-align: center;
    margin-bottom: 20px;
}
.btn-print {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    background: #7a5c00;
    color: #fff;
    border: none;
    border-radius: 6px;
    padding: 11px 24px;
    font-size: 15px;
    font-weight: 600;
    font-family: Arial, sans-serif;
    cursor: pointer;
    text-decoration: none;
    transition: opacity .15s;
}
.btn-print:hover { opacity: .85; }

/* Badge sorteo oficial */
.cert-official-badge {
    background: #f0fdf4;
    border: 1px solid #86efac;
    border-left: 4px solid #22c55e;
    border-radius: 4px;
    padding: 10px 16px;
    font-size: 13px;
    color: #14532d;
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin-bottom: 28px;
    font-weight: 600;
}
.cert-unofficial-warn {
    background: #fef2f2;
    border: 1px solid #fca5a5;
    border-left: 4px solid #ef4444;
    border-radius: 4px;
    padding: 10px 16px;
    font-size: 13px;
    color: #7f1d1d;
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin-bottom: 28px;
}

/* Aviso sorteo múltiple */
.cert-multi-warn {
    background: #fffbeb;
    border: 1px solid #f59e0b;
    border-left: 4px solid #d97706;
    border-radius: 4px;
    padding: 12px 16px;
    font-size: 13px;
    color: #92400e;
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin-bottom: 28px;
}
.cert-multi-warn strong { font-weight: 700; }

/* Method box */
.cert-method-box {
    background: #fffbf0;
    border: 1px solid #ead98a;
    border-left: 3px solid #b8860b;
    border-radius: 4px;
    padding: 12px 16px;
    font-size: 13px;
    color: #5a4200;
    line-height: 1.7;
    font-style: italic;
    font-family: Georgia, serif;
}

/* Panel de bloqueo (solo visible en pantalla, no en impresión) */
.cert-lock-panel {
    max-width: 800px;
    margin: 20px auto 0;
    background: #fff;
    border: 1px solid #d4b896;
    border-radius: 4px;
    padding: 18px 24px;
    font-family: Arial, sans-serif;
}
.cert-lock-title { font-size: 15px; font-weight: 700; color: #7a5c00; margin-bottom: 6px; }
.cert-lock-title-active { color: #15803d; }
.cert-lock-desc { font-size: 13px; color: #666; margin-bottom: 14px; line-height: 1.5; }
.cert-lock-days { display: flex; gap: 8px; flex-wrap: wrap; }
.cert-btn-lock-day {
    flex: 1; min-width: 60px;
    background: #fdfaf4;
    border: 1px solid #d4b896;
    color: #7a5c00;
    border-radius: 4px;
    padding: 8px 4px;
    font-size: 13px; font-weight: 600;
    cursor: pointer; font-family: inherit;
    transition: background .15s;
}
.cert-btn-lock-day:hover { background: #f0e6cc; }
.cert-btn-lock-day:disabled { opacity: .45; cursor: default; }
.cert-btn-unlock {
    margin-top: 10px; width: 100%;
    background: #fdfaf4; border: 1px solid #d4b896;
    color: #7a5c00; border-radius: 4px;
    padding: 9px; font-size: 13px; font-weight: 600;
    cursor: pointer; font-family: inherit;
}
.cert-btn-unlock:hover { background: #f0e6cc; }

@media print {
    .no-print { display: none; }
    .cert-lock-panel { display: none; }
    body { background: #fff; padding: 0; }
    .cert-wrap { box-shadow: none; border: 1px solid #ccc; }
}
</style>
</head>
<body>

<div class="no-print">
    <button class="btn-print" onclick="window.print()"><?= cs('print_btn') ?></button>
</div>

<div class="cert-wrap">

    <div class="cert-header">
        <span class="cert-icon">🏆</span>
        <h1><?= cs('title') ?></h1>
        <div class="cert-subtitle"><?= cs('cert_subtitle_full') ?></div>
    </div>

    <div class="cert-body">

        <!-- Video -->
        <div class="cert-section">
            <div class="cert-section-title"><?= cs('video') ?></div>
            <div class="cert-video-title"><?= $video_title ?></div>
            <a class="cert-video-link"
               href="https://www.youtube.com/watch?v=<?= $video_id ?>"
               target="_blank" rel="noopener">
                https://www.youtube.com/watch?v=<?= $video_id ?>
            </a>
            <div class="cert-video-id">ID: <?= $video_id ?></div>
        </div>

        <!-- Detalles del sorteo -->
        <div class="cert-section">
            <div class="cert-section-title"><?= cs('draw_details') ?></div>
            <div class="cert-details">
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('drawn_at') ?></span>
                    <span class="cert-detail-value"><?= esc($drawn_at_fmt) ?></span>
                </div>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('draw_number') ?></span>
                    <span class="cert-detail-value" style="<?= $draw_number > 1 ? 'color:#b45309;font-weight:800' : '' ?>">#<?= $draw_number ?></span>
                </div>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= count($winners) === 1 ? cs('winner_label') : cs('winners_label') ?></span>
                    <span class="cert-detail-value"><?= count($winners) ?></span>
                </div>
                <?php if (!empty($backups)): ?>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('backups') ?></span>
                    <span class="cert-detail-value"><?= count($backups) ?></span>
                </div>
                <?php endif; ?>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('unique_user_label') ?></span>
                    <span class="cert-detail-value"><?= $unique_users ? cs('unique_user_yes') : cs('unique_user_no') ?></span>
                </div>
                <?php if ($keyword !== ''): ?>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('keyword_label') ?></span>
                    <span class="cert-detail-value"><?= esc($keyword) ?></span>
                </div>
                <?php endif; ?>
                <?php if ($date_from !== ''): ?>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('date_from_label') ?></span>
                    <span class="cert-detail-value"><?= esc($date_from) ?></span>
                </div>
                <?php endif; ?>
                <?php if ($date_to !== ''): ?>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('date_to_label') ?></span>
                    <span class="cert-detail-value"><?= esc($date_to) ?></span>
                </div>
                <?php endif; ?>
                <div class="cert-detail-item">
                    <span class="cert-detail-label"><?= cs('valid_until') ?></span>
                    <span class="cert-detail-value"><?= esc($valid_until_fmt) ?></span>
                </div>
            </div>
        </div>

        <?php if ($is_official): ?>
        <div class="cert-official-badge">
            <?= cs('official_badge') ?> — <?= cs('official_until', gmdate('d/m/Y H:i', strtotime($cert_lock['locked_until'])) . ' UTC') ?>
        </div>
        <?php elseif ($is_unofficial): ?>
        <div class="cert-unofficial-warn">
            ⚠ <?= cs('unofficial_warn') ?>
        </div>
        <?php elseif ($draw_number > 1): ?>
        <div class="cert-multi-warn">
            <strong>⚠ <?= cs('draw_number_warning', $draw_number) ?></strong>
        </div>
        <?php endif; ?>

        <!-- Método de sorteo -->
        <div class="cert-section">
            <div class="cert-section-title"><?= cs('method_title') ?></div>
            <div class="cert-method-box">
                <?= cs('method_body', count($winners)) ?>
            </div>
        </div>

        <!-- Ganadores -->
        <div class="cert-section">
            <div class="cert-section-title"><?= count($winners) === 1 ? cs('winner_label') : cs('winners_label') ?></div>
            <ul class="cert-winner-list">
            <?php
            $medals    = ['🥇', '🥈', '🥉'];
            $posClasses = ['pos-1', 'pos-2', 'pos-3'];
            foreach ($winners as $i => $w):
                $pos      = (int)($w['position'] ?? ($i + 1));
                $posLabel = $medals[$pos - 1] ?? '#' . $pos;
                $posClass = $posClasses[$pos - 1] ?? '';
                $text     = $w['text'] ?? '';
                if (mb_strlen($text) > 200) $text = mb_substr($text, 0, 200) . '…';
                $base_cid = explode('.', $w['comment_id'] ?? '')[0];
                $yt_link  = 'https://www.youtube.com/watch?v=' . urlencode($sorteo['video_id']) .
                            '&lc=' . urlencode($base_cid);
            ?>
            <li class="cert-winner-item">
                <div class="cert-winner-pos <?= esc($posClass) ?>"><?= $posLabel ?></div>
                <div class="cert-winner-body">
                    <div class="cert-winner-author">@<?= esc($w['author'] ?? '') ?></div>
                    <?php if ($text): ?>
                    <div class="cert-winner-comment">"<?= esc($text) ?>"</div>
                    <?php endif; ?>
                    <a class="cert-winner-link" href="<?= esc($yt_link) ?>"
                       target="_blank" rel="noopener"><?= cs('view_comment') ?></a>
                </div>
            </li>
            <?php endforeach; ?>
            </ul>
        </div>

        <?php if (!empty($backups)): ?>
        <!-- Suplentes -->
        <div class="cert-section">
            <div class="cert-section-title"><?= cs('backups') ?></div>
            <ul class="cert-backup-list">
            <?php foreach ($backups as $i => $w):
                $pos     = (int)($w['position'] ?? ($i + 1));
                $text    = $w['text'] ?? '';
                if (mb_strlen($text) > 200) $text = mb_substr($text, 0, 200) . '…';
                $base_cid = explode('.', $w['comment_id'] ?? '')[0];
                $yt_link  = 'https://www.youtube.com/watch?v=' . urlencode($sorteo['video_id']) .
                            '&lc=' . urlencode($base_cid);
            ?>
            <li class="cert-backup-item">
                <div class="cert-backup-pos"><?= $pos ?></div>
                <div class="cert-backup-body">
                    <div class="cert-backup-label"><?= cs('backup_badge') ?></div>
                    <div class="cert-backup-author">@<?= esc($w['author'] ?? '') ?></div>
                    <?php if ($text): ?>
                    <div class="cert-backup-comment">"<?= esc($text) ?>"</div>
                    <?php endif; ?>
                    <a class="cert-backup-link" href="<?= esc($yt_link) ?>"
                       target="_blank" rel="noopener"><?= cs('view_comment') ?></a>
                </div>
            </li>
            <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>

    </div><!-- /cert-body -->

    <?php
    $verify_url = 'https://mammoli.ar/sorteo/verificar.php'
        . '?v=' . urlencode($id)
        . '&h=' . urlencode($verify_hash)
        . '&lang=' . $lang;
    $qr_src = 'https://api.qrserver.com/v1/create-qr-code/'
        . '?size=100x100&color=7a5c00&bgcolor=fdfaf4&data=' . urlencode($verify_url);
    ?>
    <div class="cert-footer">
        <div class="cert-footer-inner">
            <div class="cert-footer-text">
                <div class="cert-footer-hash">
                    <?= cs('verification') ?>: <strong><?= esc($verify_hash) ?></strong>
                </div>
                <div class="cert-footer-meta">
                    <?= cs('generated_by') ?> <a href="https://mammoli.ar/sorteo/" target="_blank">mammoli.ar/sorteo</a>
                    &nbsp;·&nbsp; ID: <?= esc($id) ?>
                </div>
            </div>
            <div class="cert-footer-qr">
                <a href="<?= esc($verify_url) ?>" target="_blank" rel="noopener">
                    <img src="<?= esc($qr_src) ?>" width="100" height="100" alt="<?= cs('scan_to_verify') ?>">
                </a>
                <div class="cert-footer-qr-label"><?= cs('scan_to_verify') ?></div>
            </div>
        </div>
    </div>

</div><!-- /cert-wrap -->

<!-- Panel de bloqueo — solo visible si la sesión es propietaria del sorteo -->
<div id="cert-lock-panel" class="cert-lock-panel" style="display:none">
    <div id="cert-lock-view-unlocked">
        <div class="cert-lock-title"><?= cs('lock_panel_title') ?></div>
        <div class="cert-lock-desc"><?= cs('lock_panel_desc') ?></div>
        <div class="cert-lock-days">
            <button class="cert-btn-lock-day" data-days="1"><?= cs('lock_1d') ?></button>
            <button class="cert-btn-lock-day" data-days="3"><?= cs('lock_3d') ?></button>
            <button class="cert-btn-lock-day" data-days="7"><?= cs('lock_7d') ?></button>
            <button class="cert-btn-lock-day" data-days="30"><?= cs('lock_30d') ?></button>
        </div>
    </div>
    <div id="cert-lock-view-active" style="display:none">
        <div class="cert-lock-title cert-lock-title-active"><?= cs('lock_active_title') ?></div>
        <div id="cert-lock-active-desc" class="cert-lock-desc"></div>
        <button id="cert-btn-unlock" class="cert-btn-unlock"><?= cs('lock_btn_unlock') ?></button>
    </div>
</div>

<script>
(function() {
    var certId    = <?= json_encode($id) ?>;
    var activeDesc = <?= json_encode(cs('lock_active_desc', '')) ?>;

    // Verificar que esta sesión es propietaria del sorteo
    var candidate = null;
    try { candidate = JSON.parse(localStorage.getItem('sorteoLockCandidate')); } catch(e) {}
    if (!candidate || candidate.id !== certId) return;
    if (Date.now() - (candidate.ts || 0) > 8 * 3600 * 1000) return;

    var panel = document.getElementById('cert-lock-panel');
    panel.style.display = '';

    function showView(view, untilFmt) {
        document.getElementById('cert-lock-view-unlocked').style.display = view === 'unlocked' ? '' : 'none';
        document.getElementById('cert-lock-view-active').style.display   = view === 'active'   ? '' : 'none';
        if (view === 'active' && untilFmt) {
            document.getElementById('cert-lock-active-desc').textContent =
                activeDesc.replace('{0}', untilFmt);
        }
    }

    // Consultar estado actual
    fetch('api.php?action=get_lock&id=' + encodeURIComponent(certId))
        .then(function(r) { return r.json(); })
        .then(function(d) { showView(d.locked && d.is_owner ? 'active' : 'unlocked', d.locked_until_fmt); })
        .catch(function() {});

    document.querySelectorAll('.cert-btn-lock-day').forEach(function(btn) {
        btn.addEventListener('click', function() {
            document.querySelectorAll('.cert-btn-lock-day').forEach(function(b) { b.disabled = true; });
            fetch('api.php?action=lock', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({id: certId, days: parseInt(btn.dataset.days)})
            })
            .then(function(r) { return r.json(); })
            .then(function(d) {
                if (d.locked) { location.reload(); }
                else { document.querySelectorAll('.cert-btn-lock-day').forEach(function(b) { b.disabled = false; }); }
            })
            .catch(function() { document.querySelectorAll('.cert-btn-lock-day').forEach(function(b) { b.disabled = false; }); });
        });
    });

    document.getElementById('cert-btn-unlock').addEventListener('click', function() {
        fetch('api.php?action=unlock', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({id: certId})
        })
        .then(function(r) { return r.json(); })
        .then(function(d) { if (d.unlocked) location.reload(); });
    });
})();
</script>

</body>
</html>
