<?php
define('YT_API_KEY',        'TU_API_KEY_AQUI');
define('SORTEO_ADMIN_KEY',  'CLAVE_SECRETA_ADMIN');
define('SORTEO_HMAC_SECRET','CLAVE_HMAC_SECRETA_AQUI');
define('TG_BOT_TOKEN',     'TOKEN_DEL_BOT_TELEGRAM');
define('TG_CHAT_ID',       'CHAT_ID_DESTINO');
